version: "3"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8888:8888
      - 8866:8866
    volumes:
      - ./data:/root/app
      - ./jupyter-config:/root/.jupyter
